"""empty message

Revision ID: 51ae5934dfba
Revises: 
Create Date: 2019-06-29 12:20:16.953326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ae5934dfba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('idn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('race', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idn')
    )
    op.create_index(op.f('ix_character_gender'), 'character', ['gender'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    op.create_index(op.f('ix_character_race'), 'character', ['race'], unique=False)
    op.create_index(op.f('ix_character_role'), 'character', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_role'), table_name='character')
    op.drop_index(op.f('ix_character_race'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_gender'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
