"""empty message

Revision ID: f0fcd77b9c60
Revises: 51ae5934dfba
Create Date: 2019-06-29 19:11:17.643701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fcd77b9c60'
down_revision = '51ae5934dfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('idn', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idn')
    )
    op.create_table('choice',
    sa.Column('idn', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('scenario_idn', sa.Integer(), nullable=False),
    sa.Column('target_idn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_idn'], ['scenario.idn'], ),
    sa.ForeignKeyConstraint(['target_idn'], ['scenario.idn'], ),
    sa.PrimaryKeyConstraint('idn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice')
    op.drop_table('scenario')
    # ### end Alembic commands ###
